services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.1.3.23
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"
    volumes:
      - ./docker-init.sql:/docker-entrypoint-initdb.d/docker-init.sql
      - clickhouse_data:/var/lib/clickhouse
    environment: 
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data:
