name: publish docker

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set SHORT_SHA variable
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV

      - name: Get version tag
        id: version_tag
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build, tag, and push image to ghcr
        env:
          REGISTRY_TAG: "ghcr.io/steelcake/cherry-pipelines"
        run: |
          docker buildx create --use --name cachebuilder
          docker buildx build --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache,mode=max --tag $REGISTRY_TAG:$VERSION --tag $REGISTRY_TAG:$SHORT_SHA --load .
          docker push $REGISTRY_TAG:$VERSION
          docker push $REGISTRY_TAG:$SHORT_SHA
